
def prompt_map():
      return {
        "doctor": "A confident doctor in a white coat, stethoscope around neck, standing in a hospital",
        "engineer": "A professional engineer wearing a hard hat, holding blueprints at a construction site",
        "teacher": "A friendly teacher writing on a classroom blackboard with students in the background",
        "lawyer": "A smart lawyer standing in a courtroom, wearing a suit and holding legal documents",
        "police officer": "A brave police officer in uniform, standing next to a patrol car with flashing lights",
        "chef": "A professional chef cooking in a modern kitchen, wearing a white chef hat and apron",
        "scientist": "A focused scientist working in a futuristic lab with test tubes and glowing chemicals",
        "astronaut": "An astronaut in a space suit floating outside a space station with Earth in the background",
        "pilot": "A commercial airline pilot in uniform standing beside an airplane on a runway",
        "nurse": "A caring nurse assisting a patient in a hospital room",
        "firefighter": "A heroic firefighter in full gear rescuing someone from a burning building",
        "artist": "An imaginative artist painting a canvas in a sunlit studio",
        "musician": "A musician playing guitar on a stage with colorful lights and crowd cheering",
        "singer": "A pop singer performing on a big stage with fans holding lightsticks",
        "dancer": "A professional dancer performing a dramatic ballet move on stage",
        "photographer": "A street photographer capturing moments with a DSLR in an urban setting",
        "actor": "A movie actor dressed in costume, standing on a film set",
        "writer": "A novelist writing in a cozy room with vintage decor and a typewriter",
        "journalist": "A field journalist reporting news live with a mic and camera crew",
        "fashion designer": "A fashion designer sketching a new dress in a trendy boutique",
        "model": "A fashion model walking the runway in glamorous clothing",
        "architect": "An architect reviewing a building model in a modern office",
        "mechanic": "A car mechanic repairing a vehicle in a garage, wearing overalls and gloves",
        "driver": "A professional race car driver standing next to a sports car on a track",
        "farmer": "A farmer working in a green field with a tractor in the background",
        "plumber": "A plumber fixing pipes under a sink with a toolbox beside",
        "electrician": "An electrician repairing a fuse box wearing a safety helmet and gloves",
        "carpenter": "A skilled carpenter cutting wood in a workshop",
        "software developer": "A programmer coding on multiple screens in a tech office",
        "game developer": "A game developer testing a VR game with a headset and controllers",
        "web designer": "A creative web designer working on a UX layout on a large monitor",
        "data scientist": "A data scientist analyzing graphs and charts in a high-tech office",
        "cybersecurity expert": "A cybersecurity analyst monitoring threats on dark screens",
        "biologist": "A marine biologist exploring coral reefs underwater in diving gear",
        "chemist": "A chemist mixing colorful liquids in beakers in a lab",
        "physicist": "A physicist writing formulas on a glass board in a lab",
        "economist": "An economist presenting trends and charts in a formal meeting",
        "accountant": "An accountant reviewing financial reports at a desk",
        "banker": "A banker interacting with a client in a sleek bank branch",
        "barista": "A barista making latte art in a cozy coffee shop",
        "waiter": "A restaurant waiter taking orders with a smile",
        "bartender": "A bartender mixing drinks behind a lively bar",
        "flight attendant": "A flight attendant welcoming passengers aboard an airplane",
        "event planner": "An event planner arranging decorations at a wedding venue",
        "interior designer": "An interior designer presenting a home layout to clients",
        "real estate agent": "A real estate agent showing a modern apartment to buyers",
        "trainer": "A personal trainer guiding a workout session in a gym",
        "yoga instructor": "A yoga instructor leading a sunrise yoga class outdoors",
        "therapist": "A therapist talking with a patient in a calming office",
        "psychologist": "A psychologist observing behavior in a therapy session",
        "veterinarian": "A veterinarian examining a pet dog in a clinic",
        "florist": "A florist arranging a colorful bouquet in a flower shop",
        "librarian": "A librarian organizing books in a quiet library",
        "news anchor": "A news anchor delivering headlines in a newsroom",
        "delivery driver": "A delivery driver handing a package to a happy customer",
        "social media manager": "A social media manager planning posts on a laptop in a café",
        "influencer": "A lifestyle influencer filming a vlog with a camera on a tripod",
        "content creator": "A content creator editing videos on a high-spec setup",
        "voice actor": "A voice actor recording in a soundproof studio",
        "DJ": "A DJ playing music at a night party with neon lights",
        "interpreter": "An interpreter translating in a live conference with a headset",
        "historian": "A historian examining old manuscripts in an archive",
        "detective": "A detective inspecting clues at a crime scene",
        "military officer": "A military officer giving orders in a tactical environment",
        "sailor": "A sailor navigating a ship through the ocean",
        "diver": "A deep-sea diver exploring underwater caves",
        "geologist": "A geologist studying rock formations in a desert",
        "environmentalist": "An environmentalist planting trees in a green campaign",
        "pilot trainer": "A flight instructor guiding a student in a simulator",
        "paramedic": "A paramedic assisting a patient in an ambulance",
        "bodyguard": "A bodyguard protecting a VIP in a crowded place",
        "nanny": "A nanny playing with children in a bright living room",
        "call center agent": "A customer support agent talking on a headset in a call center",
        "magician": "A magician performing tricks on stage with a cheering audience",
        "comedian": "A stand-up comedian entertaining the crowd in a comedy club",
        "park ranger": "A park ranger guiding tourists in a forest trail",
        "zookeeper": "A zookeeper feeding animals in a zoo habitat",
        "researcher": "A researcher analyzing data on a lab computer",
        "editor": "A book editor reviewing manuscripts at a desk",
        "translator": "A translator converting documents between languages on a laptop",
        "fashion stylist": "A fashion stylist preparing a model for a photoshoot",
        "skincare specialist": "A skincare specialist applying treatment in a spa",
        "choreographer": "A choreographer directing dancers in a rehearsal studio",
        "voice coach": "A voice coach training a singer in a music room",
        "tattoo artist": "A tattoo artist working on a design in a tattoo parlor",
        "hair stylist": "A hair stylist cutting and styling hair in a salon",
        "makeup artist": "A makeup artist applying bridal makeup with brushes",
        "auctioneer": "An auctioneer calling bids in a busy auction hall",
        "judge": "A judge sitting at the bench in a courtroom with gavel",
        "prosecutor": "A prosecutor presenting evidence during a trial",
        "entrepreneur": "An entrepreneur pitching an idea in a business meeting",
        "stock trader": "A stock trader monitoring market trends on multiple screens",
        "logistics manager": "A logistics manager tracking shipments in a control room",
        "security analyst": "A security analyst reviewing system alerts in an IT center",
        "UX designer": "A UX designer testing user flows on a digital product",
        "robotics engineer": "A robotics engineer assembling a robot arm in a tech lab"
  }